title:        wizztjh
tagline:      'A humble blog from a software engineer that focus on web development and agile/scrum'
description:  ''
url:          http://github.com/wizztjh
author:
  name:       'Tee Jia Hen'
  email:      'wizztjh@gmail.com'
markdown:     redcarpet
permalink:    pretty
highlighter:  pygments
paginate:     5
kramdown:
  input: GFM
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
